version: '3'
services:
  database:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=2424288
    volumes:
      - ./database_deploy/pg_hba.conf:/var/lib/data/pg_hba.conf
      - ./database_deploy/schema.sql:/docker-entrypoint-initdb.d/1.sql
    container_name: devanmejia-applist-db

  applist:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://localhost:8080
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=2424288
      - REMEMBER_ME_KEY=devanmejia
    container_name: devanmejia-applist-jar
    depends_on:
      - "database"
